# -*- coding: utf-8 -*-
"""MAANG_Stock_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gvkv_SLJAPqoJ5cREWPfjP11WvG3OlT0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd

amazon = pd.read_csv('/AMAZON_daily.csv')
apple = pd.read_csv('/APPLE_daily.csv')
google = pd.read_csv('/GOOGLE_daily.csv')
meta = pd.read_csv('/META_daily.csv')
netflix = pd.read_csv('/NETFLIX_daily.csv')

amazon.head()

amazon['Company'] = 'Amazon'
apple['Company'] = 'Apple'
google['Company'] = 'Google'
meta['Company'] = 'Meta'
netflix['Company'] = 'Netflix'

amazon['Date'] = pd.to_datetime(amazon['Date'])
apple['Date'] = pd.to_datetime(apple['Date'])
google['Date'] = pd.to_datetime(google['Date'])
meta['Date'] = pd.to_datetime(meta['Date'])
netflix['Date'] = pd.to_datetime(netflix['Date'])

maang_df = pd.concat([amazon, apple, google, meta, netflix], axis=0)
maang_df.head()

# Dataset ka summary
maang_df.info()

# Missing values check
maang_df.isnull().sum()

# Basic statistics
maang_df.describe()

maang_df = maang_df.dropna()

maang_df.columns

maang_df['Daily_Return'] = maang_df['Adj Close'].pct_change()

maang_df['MA_50'] = maang_df['Adj Close'].rolling(window=50).mean()
maang_df['MA_200'] = maang_df['Adj Close'].rolling(window=200).mean()

maang_df['Price_Change'] = maang_df['High'] - maang_df['Low']

maang_df.head()

# Close Price Trend (All Companies)

import matplotlib.pyplot as plt

plt.figure(figsize=(15,7))
for company in maang_df['Company'].unique():
    temp = maang_df[maang_df['Company'] == company]
    plt.plot(temp['Date'], temp['Adj Close'], label=company)

plt.title('MAANG Companies Adjusted Close Price Trend')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.show()

# Daily Returns Histogram

google_df = maang_df[maang_df['Company'] == 'Google']
plt.hist(google_df['Daily_Return'].dropna(), bins=50)
plt.title('Google Daily Returns Distribution')
plt.show()

# Correlation Matrix

pivot_df = maang_df.pivot(index='Date', columns='Company', values='Adj Close')
correlation = pivot_df.corr()
print(correlation)

# Top performing / least performing days → Trend insights

maang_df.sort_values('Daily_Return', ascending=False).head(5)

# Volatility Analysis

plt.figure(figsize=(12,5))
for company in maang_df['Company'].unique():
    temp = maang_df[maang_df['Company']==company]
    plt.plot(temp['Date'], temp['Price_Change'], label=company)

plt.title('Daily Price Change (Volatility) of MAANG Companies')
plt.xlabel('Date')
plt.ylabel('Price Change (High-Low)')
plt.legend()
plt.show()

# INSIGHTS

# Top 5 growth days per company
top_growth = maang_df.groupby('Company')['Daily_Return'].nlargest(5)
print(top_growth)

# EVENT / SPECIAL DAY ANALYSIS

 # Filter 2020 COVID crash period
covid_df = maang_df[(maang_df['Date'] >= '2020-02-15') & (maang_df['Date'] <= '2020-04-15')]
covid_df.groupby('Company')['Adj Close'].min()

# EXPORT CLEAN CSV

maang_df.to_csv('MAANG_Stock_Analysis.csv', index=False)



